### ISSUE TITLE
10/14 은철님 숙제

### ISSUE THREAD

**Issue by jinainkorea** [InfoShareCrew/Main#20]
건의게시판 관련해서 일반회원 작성, 수정 기능 완성해주세요!
매니저 관련된 기능은 지금 안 하셔도 됩니다~
기능과 이슈 단위로 커밋하는거 잊지마시구요, 다 하시면 푸시하시고 PR요청해주세용

**Comment by LEEEUNCHEOL96** [comment]
완료우~!.😊

**Comment by jinainkorea** [comment]
잘하셨습니당~!
