### ISSUE TITLE
10/14 승수님 숙제

### ISSUE THREAD

**Issue by jinainkorea** [InfoShareCrew/Main#21]
요구사항 정의서에 표시한 완료 못 한 기능 중에 하나만 완료해주세요!
기능과 이슈 단위로 커밋하는거 잊지마시구요, 다 하시면 푸시하시고 PR요청해주세용

**Comment by anyeok** [comment]
- 기존 로그인 할 때 이메일 형식으로 로그인 한 후 메인 페이지로 리다이렉트 하도록 수정 완료했습니다.
