### ISSUE TITLE
10/15 - 은철님 : 카페 개설 기능

### ISSUE THREAD

**Issue by jinainkorea** [InfoShareCrew/Main#26]
- 카페 개설 기능
  카페 관련 모든 엔티티나 클래스 만들어 주시고 카페 개설 기능 완료해주세요.
- 첫번째 항목 완료하셨으면 태그 기능 최대한 해주세요.

무리는 하시지 말고, 하는대로 완료하면 커밋 및 푸시 해주세요

**Comment by jinainkorea** [comment]
수정 요청! #31

**Comment by LEEEUNCHEOL96** [comment]
완료✅
