### ISSUE TITLE
10/15 - 승수님 숙제 : 이웃 맺기 1

### ISSUE THREAD

**Issue by jinainkorea** [InfoShareCrew/Main#30]
- 이웃 맺기 기능

간단하게만 해주세용

**Comment by anyeok** [comment]
- 이웃 구현 완료했습니다.
- 왼쪽 인덱스에서 이웃 누르면 확인할 수 있고, 이웃 추가 기능은 일단 만들어두었는데, 팀원간의 상의 후에 추가해야할 것 같습니다.
